apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: myapp
        image: httpd:latest

